groups:
  - name: leak-radar-worker-staging
    rules:
      - alert: LeakWorkerStatusStaleStaging
        expr: leak_worker_status_age_ms > 300000
        for: 5m
        labels:
          severity: warning
          profile: staging
          service: leak-radar
          team: leak-platform
          owner: security-ops
        annotations:
          summary: "[staging] worker status stale"
          description: "status age is above 5 minutes in staging"

      - alert: LeakWorkerStatusStaleCriticalStaging
        expr: leak_worker_status_age_ms > 900000
        for: 10m
        labels:
          severity: critical
          profile: staging
          service: leak-radar
          team: leak-platform
          owner: security-ops
        annotations:
          summary: "[staging] worker status critically stale"
          description: "status age is above 15 minutes in staging"

      - alert: LeakWorkerAutoErrorRatioHighStaging
        expr: leak_worker_pipeline_last_auto_error_ratio > 0.3
        for: 10m
        labels:
          severity: warning
          profile: staging
          service: leak-radar
          team: leak-platform
          owner: security-ops
        annotations:
          summary: "[staging] auto error ratio high"
          description: "auto error ratio is above 30% in staging"

      - alert: LeakWorkerAutoErrorRatioCriticalStaging
        expr: leak_worker_pipeline_last_auto_error_ratio > 0.6
        for: 10m
        labels:
          severity: critical
          profile: staging
          service: leak-radar
          team: leak-platform
          owner: security-ops
        annotations:
          summary: "[staging] auto error ratio critical"
          description: "auto error ratio is above 60% in staging"

      - alert: LeakWorkerCommitRateLimitExhaustedStaging
        expr: leak_worker_ratelimit_remaining{api="commits"} == 0
        for: 5m
        labels:
          severity: warning
          profile: staging
          service: leak-radar
          team: leak-platform
          owner: security-ops
        annotations:
          summary: "[staging] commit search rate limit exhausted"
          description: "commit search remaining requests is zero in staging"
