import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { DETECTION_RULESET_VERSION } from "@leak/shared";

import { DETECTION_FIXTURES } from "./detection-fixtures";

const lines: string[] = [
  "# Detection Fixtures Report",
  "",
  `- Generated at: ${new Date().toISOString()}`,
  `- Ruleset version: ${DETECTION_RULESET_VERSION}`,
  `- Fixture count: ${DETECTION_FIXTURES.length}`,
  "",
  "| Name | Expected Providers |",
  "|---|---|"
];

for (const fixture of DETECTION_FIXTURES) {
  const providers = fixture.expectedProviders.length > 0
    ? fixture.expectedProviders.join(", ")
    : "(none)";
  lines.push(`| ${fixture.name} | ${providers} |`);
}

lines.push("", "## Notes", "- This file is generated by `pnpm -w --filter @leak/worker run report:fixtures`.");

const outputPath = resolve(__dirname, "../../../../DETECTION_FIXTURES_REPORT.md");
writeFileSync(outputPath, `${lines.join("\n")}\n`, "utf8");

console.log(`[detection-fixtures-report] wrote ${outputPath}`);
